build:
  version: "8.0"

loans:
  message: "Welcome to  loans related prod APIs "
  contactDetails:
    name: "Nikil Pankaj - prod Lead"
    email: "Nnai@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267