build:
  version: "2.0"

loans:
  message: "Welcome to  loans related QA APIs "
  contactDetails:
    name: "Nikil Pankaj - QA Lead"
    email: "Nnai@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267