build:
  version: "3.0"

loans:
  message: "Welcome to  loans related local APIs "
  contactDetails:
    name: "Nikil Pankaj - local Lead"
    email: "Nnai@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267